#!/bin/bash
echo $1;

sudo cp /etc/apache2/sites-available/newsite.conf /etc/apache2/sites-available/$1.conf
sudo sed -i "s/newsite/$1/g" /etc/apache2/sites-available/$1.conf
sudo a2ensite $1.conf
echo "127.0.1.1      $1" | sudo tee -a /etc/hosts
mkdir /var/www/$1
sudo service apache2 reload
mysql -u root -proot -e "create database $1"
